export {
	type ConfigValue,
	getProjectsDir,
	getProjectsDirs,
	getCacheDir,
	getTestLogDir,
	readConfig,
	writeConfig,
	getConfigValue,
	setConfigValue,
	unsetConfigValue,
} from "./lib/config.js";
export {
	type RemoteBranchInfo,
	discoverProjects,
	discoverAllProjects,
	getChildren,
	getChildCommits,
	isDirty,
	isDetachedHead,
	hasUpstreamRef,
	hasTestConfigured,
	getMiseEnv,
	createBranchForChild,
	testBranch,
	testFix,
	hasLocalModifications,
	fetchUpstreamRef,
	computeMergeStatus,
	getNeedsRebaseBranches,
	isSkippable,
	parseBranch,
	parseRemoteBranchOutput,
	getRemoteBranchInfo,
	pruneRemote,
	getRepoOwnerAndName,
	getPatchId,
} from "./lib/git.js";
export {type PrStatuses, getPrStatuses} from "./lib/github-pr-status.js";
export {
	type SnoozedItem,
	type BranchNameItem,
	type TestResultItem,
	type CachedPrStatus,
	initDb,
	resetDb,
	getDb,
	snoozeItem,
	unsnoozeItem,
	getActiveSnoozed,
	getSnoozedSet,
	getAllSnoozed,
	getAllSnoozedForDisplay,
	clearExpiredSnoozes,
	getSnoozeHistory,
	getBranchName,
	getBranchNames,
	setBranchName,
	getTestResultsForProject,
	recordTestResult,
	getCachedPrStatuses,
	cachePrStatuses,
	invalidatePrCache,
	isCacheFresh,
	markCacheFresh,
	getCacheFreshnessByPrefix,
	getCachedMiseEnv,
	cacheMiseEnv,
	getCachedGhLogin,
	cacheGhLogin,
	getCachedUpstreamSha,
	cacheUpstreamSha,
	getCachedMergeStatuses,
	cacheMergeStatus,
	invalidateMergeStatus,
	getCachedProjectList,
	setCachedProjectList,
	getCachedChildren,
	cacheChildren,
	invalidateChildrenCache,
	getCachedTodos,
	cacheTodos,
	invalidateTodosCache,
	getAdvanceConfig,
	getAllAdvanceConfig,
	setAdvanceConfig,
} from "./lib/db.js";
export {suggestBranchNames} from "./lib/branch-namer.js";
export {
	normalizeFailureSignature,
	changeIdentity,
	RunMemory,
	type AttemptKind,
	type UnitRef,
} from "./lib/advance-progress.js";
export {renderTree, type NodeStatus, type ReportNode} from "./lib/advance-report.js";
export {resolveAdvanceConcurrency, parseAdvanceConcurrency, matchesFilters} from "./lib/advance-config.js";
export {planProject, type AdvanceUnit, type AdvancePlan} from "./lib/advance-plan.js";
export {
	AdvanceScheduler,
	createSystemProbe,
	type SchedulableUnit,
	type ResourceProbe,
	type SchedulerOptions,
	type UnitOutcome,
} from "./lib/advance-scheduler.js";
export {ensureBranchWorktree, parseWorktreeList, type BranchWorktree, type WorktreeEntry} from "./lib/worktree.js";
export {checkBaseline, type BaselineCheck} from "./lib/advance-baseline.js";
export {
	advanceProject,
	createGitActions,
	type Autonomy,
	type AdvanceEvent,
	type AdvanceActions,
	type AdvanceProjectOptions,
} from "./lib/advance.js";
export {
	GitHubIssueSchema,
	GitHubIssueLabelSchema,
	type GitHubIssue,
	IssueResultSchema,
	type IssueResult,
	fetchAssignedIssues,
	invalidateIssuesCache,
} from "./lib/github-issues.js";
export {
	GitHubProjectItemSchema,
	GitHubProjectItemLabelSchema,
	GitHubProjectSchema,
	ProjectItemResultSchema,
	type GitHubProjectItem,
	type GitHubProject,
	type ProjectItemResult,
	fetchProjects,
	fetchProjectItems,
	fetchAllProjectItems,
	invalidateProjectItemsCache,
	resetViewerLoginCache,
} from "./lib/github-projects.js";
export {
	LabelSchema,
	ReviewStatusSchema,
	type ReviewStatus,
	CheckStatusSchema,
	type CheckStatus,
	TestStatusSchema,
	type TestStatus,
	MergeStateStatusSchema,
	type MergeStateStatus,
	CategorySchema,
	type Category,
	TransitionSchema,
	type Transition,
	type StateTransition,
	STATE_MACHINE,
	getTransitionsFrom,
	getTransitionsTo,
	applyTransition,
	mapProjectStatusToCategory,
	ProjectInfoSchema,
	type ProjectInfo,
	ChildCommitSchema,
	type ChildCommit,
	GitChildResultSchema,
	type GitChildResult,
	RunClaudeCommandInputSchema,
	type RunClaudeCommandInput,
	TaskTypeSchema,
	type TaskType,
	TaskQueueJobSchema,
	type TaskQueueJob,
	TestQueueJobSchema,
	type TestQueueJob,
	PlanStatusSchema,
	type PlanStatus,
	TodoItemSchema,
	type TodoItem,
	ActionLogEntrySchema,
	type ActionLogEntry,
	ActionResultSchema,
	type ActionResult,
	ProjectBoardItemSchema,
	type ProjectBoardItem,
	SnoozedChildSchema,
	type SnoozedChild,
	PushChildInputSchema,
	type PushChildInput,
	TestChildInputSchema,
	type TestChildInput,
	SnoozeChildInputSchema,
	type SnoozeChildInput,
	UnsnoozeChildInputSchema,
	type UnsnoozeChildInput,
	CancelTestInputSchema,
	type CancelTestInput,
	CreatePrInputSchema,
	type CreatePrInput,
	RefreshChildInputSchema,
	type RefreshChildInput,
	CreateBranchInputSchema,
	type CreateBranchInput,
	DeleteBranchInputSchema,
	type DeleteBranchInput,
	ForcePushInputSchema,
	type ForcePushInput,
	RenameBranchInputSchema,
	type RenameBranchInput,
	ApplyFixesInputSchema,
	type ApplyFixesInput,
	RebaseLocalInputSchema,
	type RebaseLocalInput,
	MergePrInputSchema,
	type MergePrInput,
} from "./lib/schemas.js";
export {
	type TodoTask,
	parseTodoContent,
	parseTodoFile,
	findTodoTasks,
	findIncompleteTodoTasks,
} from "./lib/todo-parser.js";
export {
	isGitHubRateLimited,
	markGitHubRateLimited,
	resetGitHubRateLimit,
	detectRateLimitError,
	getGitHubRateLimitState,
	type GitHubRateLimitState,
} from "./lib/rate-limit.js";
export {mapWithConcurrency} from "./lib/concurrency.js";
export {
	type LogCategory,
	type LogEntry,
	captureLogs,
	clearLogBuffer,
	getRecentLogs,
	subscribeLogs,
	unsubscribeLogs,
	writeLogEntry,
} from "./services/logger.js";
export {type CreatePrParams, createPullRequest, resetRepositoryIdCache} from "./lib/github-prs.js";
export {
	type GitHubClient,
	createTestClient,
	getGitHubClient,
	setGitHubClient,
	resetGitHubClient,
} from "./services/github-client.js";
